version: '3.2'

services:
    dashboard:
        extends:
            file: ./dashboard/app.yml
            service: dashboard
        depends_on:
            - db_backend
            - mqtt_broker
    mqtt_broker:
        extends:
            file: ./mqtt_broker/app.yml
            service: mqtt_broker
    db_backend:
        extends:
            file: ./DB_Backend/app.yml
            service: db_backend
    collects:
        extends:
            file: ./CollectData/app.yml
            service: collects
        depends_on:
            - db_backend
            - mqtt_broker

networks:
  internal:
    name: home  

