services:
  collects:
    build: .
    privileged: true
    working_dir: /app
    command: "python collect.py"
    volumes:
      - ./logs/:/app/logs/
    networks:
      internal:
        aliases:
          - collect.docker.local
    restart: unless-stopped
